# BlueMap2PlotSquared configuration.

# Number of ticks to wait between every update. The default of 6000 means every 5 minutes.
# Needs to be at least 2 ticks more than the amount of worlds loaded on your server.
updateInterval: 6000

# Markerset display name in the sidebar of Bluemap's webinterface.
markerSetName: "Liste des plots"

# If set to true, users must manually activate the markerset(s) in their sidebar before being able to see the regions on the map.
hideMarkerSet: false

# Valid Placeholders are: %name%, %id%.
markerLabel: "%name% (%id%)"

# Valid Placeholders are: %name%, %id%, %owner%, %members%, %trusted%, %all_members%, %description%, %like%, %dislike%.
html: |-
  <div style="width:244px;display:flex;flex-direction:column;gap:10px;padding:10px;">
    <div style="display:flex;justify-content:space-between;align-items:center;">
      %name%
      <div style="font-size:14px;line-height:14px;color:var(--theme-fg-light);">%id%</div>
    </div>
    <div style="text-align:center;font-size:14px;line-height:14px;color:var(--theme-fg-light);">%description%</div>
  </div>
  <hr>
  <div style="display:flex;gap:10px;align-items:center;padding:10px;">
    <div style="width:100px;">Propriétaire</div>
    <div style="font-size:14px;line-height:14px;color:var(--theme-fg-light);">%owner%</div>
  </div>
  <hr>
  <div style="display:flex;gap:10px;align-items:center;padding:10px;">
    <div style="width:100px;">Membres</div>
    <div style="display: flex;flex-direction: column;font-size:14px;line-height:14px;color:var(--theme-fg-light);">%all_members%</div>
  </div>
  <hr>
  <div style="display:flex;flex-direction:row;justify-content:center;align-items:center;gap:100px;padding:10px;">
    <div style="display:flex;flex-direction:row;justify-content:center;gap:10px;align-items:center;">
      <svg title="J'aime" width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm3.5-9c.83 0 1.5-.67 1.5-1.5S16.33 8 15.5 8 14 8.67 14 9.5s.67 1.5 1.5 1.5zm-7 0c.83 0 1.5-.67 1.5-1.5S9.33 8 8.5 8 7 8.67 7 9.5 7.67 11 8.5 11zm3.5 6.5c2.33 0 4.31-1.46 5.11-3.5H6.89c.8 2.04 2.78 3.5 5.11 3.5z" fill="currentColor"/></svg>
      <div style="display:flex;align-items:center;text-align:center;width:14px;font-size:14px;line-height:14px;color:var(--theme-fg-light);">%like%</div>
    </div>
    <div style="display:flex;flex-direction:row;justify-content:center;gap:10px;align-items:center;">
      <div style="display:flex;align-items:center;text-align:center;width:14px;font-size:14px;line-height:14px;color:var(--theme-fg-light);">%dislike%</div>
      <svg title="Je n'aime pas" width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm3.5-9c.83 0 1.5-.67 1.5-1.5S16.33 8 15.5 8 14 8.67 14 9.5s.67 1.5 1.5 1.5zm-7 0c.83 0 1.5-.67 1.5-1.5S9.33 8 8.5 8 7 8.67 7 9.5 7.67 11 8.5 11zm3.5 2.5c-2.33 0-4.31 1.46-5.11 3.5h10.22c-.8-2.04-2.78-3.5-5.11-3.5z" fill="currentColor"/></svg>
    </div>
  </div>

# Valid Placeholders are: %owner%.
htmlNoPlotName: "Plot de %owner%"
htmlNoPlotDescription: "Pas de description pour ce plot"
htmlNobody: "aucun"

# Since regions are usually 3D spaces but bluemap can only display 2D markers, a height to display the region at must be specified.
# The default of 63 will display regions at sea level.
renderHeight: 63

# Define regions visibility interval. May help servers with lots of markers.
# Negative values, also the default ones, make distances unlimited (as configured by default in BlueMap).
minDistance: 100
maxDistance: 1000

# If regions don't have an individual color and outline color set, you can configure the default values here.
# defaultFillColor is in RGBA format (RRGGBBAA).
# defaultLineColor is in RGB format (RRGGBB).
defaultFillColor: "09688A4C"
defaultLineColor: "09688A"
defaultLineWidth: 2

# Additionally to addon specific ways to configure these setting for each plot individually.
world:
  # fillColor is in RGBA format (RRGGBBAA).
  # lineColor is in RGB format (RRGGBB).
  fillColor: "09688A4C"
  lineColor: "09688A"
  lineWidth: 2

  0,0:
    # fillColor is in RGBA format (RRGGBBAA).
    # lineColor is in RGB format (RRGGBB).
    fillColor: "09688A4C"
    lineColor: "09688A"
    lineWidth: 2